INFO _internal.py:224 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO _internal.py:224 [33mPress CTRL+C to quit[0m
INFO _internal.py:224  * Restarting with stat
WARNING _internal.py:224  * Debugger is active!
INFO _internal.py:224  * Debugger PIN: 186-998-194
INFO _internal.py:224 127.0.0.1 - - [16/Jan/2023 23:35:13] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO _internal.py:224 127.0.0.1 - - [16/Jan/2023 23:35:16] "[35m[1mGET /api/v1.0/index HTTP/1.1[0m" 500 -
INFO _internal.py:224 127.0.0.1 - - [16/Jan/2023 23:35:16] "GET /api/v1.0/index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:224 127.0.0.1 - - [16/Jan/2023 23:35:16] "GET /api/v1.0/index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:224 127.0.0.1 - - [16/Jan/2023 23:35:16] "GET /api/v1.0/index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:224 127.0.0.1 - - [16/Jan/2023 23:35:16] "GET /api/v1.0/index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
ERROR demo.py:9 error
WARNING demo.py:10 warn
INFO demo.py:11 info
DEBUG demo.py:12 debug
INFO _internal.py:224 127.0.0.1 - - [16/Jan/2023 23:36:10] "GET /api/v1.0/index HTTP/1.1" 200 -
INFO _internal.py:224 127.0.0.1 - - [16/Jan/2023 23:36:10] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO _internal.py:224 127.0.0.1 - - [16/Jan/2023 23:48:16] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO _internal.py:224  * Detected change in '/home/hehangzhou/test/Flask_iHome/iHome/models.py', reloading
INFO _internal.py:224  * Restarting with stat
WARNING _internal.py:224  * Debugger is active!
INFO _internal.py:224  * Debugger PIN: 186-998-194
INFO _internal.py:224  * Detected change in '/home/hehangzhou/test/Flask_iHome/iHome/constants.py', reloading
INFO _internal.py:224  * Restarting with stat
WARNING _internal.py:224  * Debugger is active!
INFO _internal.py:224  * Debugger PIN: 186-998-194
ERROR __init__.py:98 Error: Directory migrations already exists and is not empty
